---
driver:
  name: qemu

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  multiple_converge: 2
  force_idempotency: true
  product: chef
  product_version: 12

verifier:
  name: inspec

platforms:
  - name: debian-9
    driver:
      image: stretch.qcow2

suites:
  - name: default
    run_list:
      - recipe[idempotent-export-node]
    attributes: { export-node: "idempotent" }
