---
driver:
  name: qemu

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  multiple_converge: 2
  force_idempotency: true
  product_name: chef

verifier:
  name: inspec

platforms:
  - name: debian-9-chef-12
    driver:
      image: stretch.qcow2
    provisioner:
      product_version: 12
  - name: debian-9-chef-14
    driver:
      image: stretch.qcow2
    provisioner:
      product_version: 14

suites:
  - name: default
    run_list:
      - recipe[idempotent-export-node]
    attributes: { export-node: "idempotent" }
