name             'idempotent-export-node'
maintainer       'Thomas Sarboni'
maintainer_email 'max-k@post.com'
license          'Apache-2.0'
description      'Exports node attributes to a json file'
version          '1.2.6'
source_url       'https://github.com/max-k/chef-idempotent-export-node'
issues_url       'https://github.com/max-k/chef-idempotent-export-node/issues'
supports         'ubuntu', '>=12.04'
supports         'debian', '>=7.0'
chef_version     '> 12'
